// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type AlertsResult struct {
	Items    []*DataAlert `json:"items"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type ChartsResult struct {
	Items    []*SavedChart `json:"items"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type Dashboard struct {
	ID        string         `json:"id"`
	UserID    string         `json:"userId"`
	Name      string         `json:"name"`
	IsPublic  bool           `json:"isPublic"`
	Version   int            `json:"version"`
	Widgets   map[string]any `json:"widgets"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

// Complete dashboard snapshot optimised for the builder canvas.
type DashboardBundle struct {
	ID       string         `json:"id"`
	Name     string         `json:"name"`
	IsPublic bool           `json:"isPublic"`
	Version  int            `json:"version"`
	Widgets  map[string]any `json:"widgets"`
	// All charts referenced by this dashboard's widgets.
	Charts []*SavedChart `json:"charts"`
	// Distinct datasets used by the charts — for column schema access.
	Datasets  []*Dataset `json:"datasets"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
}

type DashboardsResult struct {
	Items    []*Dashboard `json:"items"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type DataAlert struct {
	ID         string    `json:"id"`
	UserID     string    `json:"userId"`
	DatasetID  string    `json:"datasetId"`
	Name       string    `json:"name"`
	ColumnName string    `json:"columnName"`
	Condition  string    `json:"condition"`
	Threshold  float64   `json:"threshold"`
	IsEnabled  bool      `json:"isEnabled"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type Dataset struct {
	ID            string         `json:"id"`
	UserID        string         `json:"userId"`
	Name          string         `json:"name"`
	FileName      string         `json:"fileName"`
	RowCount      int            `json:"rowCount"`
	SizeBytes     int            `json:"sizeBytes"`
	Columns       map[string]any `json:"columns"`
	DataTableName string         `json:"dataTableName"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
	// Charts built on this dataset.
	Charts []*SavedChart `json:"charts"`
}

type DatasetsResult struct {
	Items    []*Dataset `json:"items"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type Kpi struct {
	ID           string    `json:"id"`
	UserID       string    `json:"userId"`
	DatasetID    string    `json:"datasetId"`
	Title        string    `json:"title"`
	Metric       string    `json:"metric"`
	Aggregation  string    `json:"aggregation"`
	TargetValue  *float64  `json:"targetValue,omitempty"`
	CurrentValue *float64  `json:"currentValue,omitempty"`
	Unit         string    `json:"unit"`
	Trend        string    `json:"trend"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type KpisResult struct {
	Items    []*Kpi    `json:"items"`
	PageInfo *PageInfo `json:"pageInfo"`
}

type PageInfo struct {
	Total      int `json:"total"`
	Page       int `json:"page"`
	Limit      int `json:"limit"`
	TotalPages int `json:"totalPages"`
}

type Query struct {
}

type SavedChart struct {
	ID          string         `json:"id"`
	UserID      string         `json:"userId"`
	DatasetID   string         `json:"datasetId"`
	Title       string         `json:"title"`
	Type        string         `json:"type"`
	XAxis       string         `json:"xAxis"`
	YAxis       string         `json:"yAxis"`
	GroupBy     string         `json:"groupBy"`
	Annotations map[string]any `json:"annotations"`
	CreatedAt   time.Time      `json:"createdAt"`
	// Parent dataset metadata (resolved via DataLoader — no N+1).
	Dataset *Dataset `json:"dataset,omitempty"`
}
