package graphql

// Resolver is the root dependency-injection container for all GraphQL resolvers.
// It holds read-only references to repositories / DB — matching the pattern used
// by existing handlers (services → repository → DB).
//
// This file WILL NOT be regenerated by gqlgen.

import (
	"neuradash/internal/repository"

	"gorm.io/gorm"
)

// Resolver holds all dependencies used by query resolvers.
// We intentionally accept concrete repository interfaces (not raw *gorm.DB) to
// stay consistent with the Repository Pattern mandated by existing code, and to
// allow unit-testing via mocks in the future.
type Resolver struct {
	// DB is kept for KPI/Alert which still use direct DB access in their handlers.
	// Resolvers for those entities mirror the same pattern.
	DB *gorm.DB

	DashboardRepo repository.DashboardRepository
	DatasetRepo   repository.DatasetRepository
	ChartRepo     repository.ChartRepository
	AlertRepo     repository.DataAlertRepository

	// DataLoader centralises batch-loading of datasets referenced by charts.
	// Initialised lazily per-request via middleware (see newDataLoaderForRequest).
	// This field is intentionally kept here so the compiler sees it, but the
	// per-request loader is stored in context.Context — see dataloader.go.
}
