package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"neuradash/internal/models"
	"fmt"

	"gorm.io/gorm"
)

// DashboardBundle is the resolver for the dashboardBundle field.
// This is the key query: returns one dashboard + its charts + their datasets
// in a SINGLE roundtrip, replacing 3-4 sequential REST calls.
func (r *queryResolver) DashboardBundle(ctx context.Context, id string) (*DashboardBundle, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	// 1. Fetch the dashboard (ownership check enforced by repo).
	dash, err := r.DashboardRepo.GetByID(ctx, id, userID)
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, nil // GraphQL: nullable return = not found
		}
		return nil, fmt.Errorf("get dashboard: %w", err)
	}

	// 2. Fetch charts that belong to datasets referenced in this dashboard's widgets.
	//    We load ALL charts for the user that reference datasets in the widget config.
	//    Strategy: get charts by user, filter by dataset IDs extracted from widgets.
	datasetIDs := extractDatasetIDsFromWidgets(dash.Widgets)

	var chartRows []models.SavedChart
	if len(datasetIDs) > 0 {
		if err := r.DB.WithContext(ctx).
			Where("user_id = ? AND dataset_id IN ?", userID, datasetIDs).
			Order("created_at desc").
			Find(&chartRows).Error; err != nil {
			return nil, fmt.Errorf("fetch bundle charts: %w", err)
		}
	}

	// 3. Batch-load datasets via DataLoader (1 query for all unique dataset IDs).
	loader := loaderFromCtx(ctx)
	if loader != nil {
		for _, did := range datasetIDs {
			loader.Schedule(did)
		}
		if ferr := loader.Flush(ctx); ferr != nil {
			return nil, ferr
		}
	}

	// 4. Map charts → GQL, attaching dataset from loader cache.
	gqlCharts := make([]*SavedChart, 0, len(chartRows))
	for i := range chartRows {
		ch := modelChartToGQL(&chartRows[i])
		if loader != nil {
			ch.Dataset = loader.Get(chartRows[i].DatasetID)
		}
		gqlCharts = append(gqlCharts, ch)
	}

	// 5. Build distinct GQL datasets slice.
	seenDS := make(map[string]struct{})
	gqlDatasets := make([]*Dataset, 0, len(datasetIDs))
	if loader != nil {
		for _, did := range datasetIDs {
			if _, ok := seenDS[did]; !ok {
				seenDS[did] = struct{}{}
				if ds := loader.Get(did); ds != nil {
					gqlDatasets = append(gqlDatasets, ds)
				}
			}
		}
	}

	// 6. Build widgets map for GQL.
	w := make(map[string]any)
	if dash.Widgets != nil {
		if mw, ok := any(dash.Widgets).(map[string]any); ok {
			w = mw
		}
	}

	return &DashboardBundle{
		ID:        dash.ID,
		Name:      dash.Name,
		IsPublic:  dash.IsPublic,
		Version:   dash.Version,
		Widgets:   w,
		Charts:    gqlCharts,
		Datasets:  gqlDatasets,
		CreatedAt: dash.CreatedAt,
		UpdatedAt: dash.UpdatedAt,
	}, nil
}

// Dashboards is the resolver for the dashboards field.
func (r *queryResolver) Dashboards(ctx context.Context, page *int, limit *int) (*DashboardsResult, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	p, l := pageDefaults(page, limit)

	rows, total, err := r.DashboardRepo.List(ctx, userID, p, l)
	if err != nil {
		return nil, fmt.Errorf("list dashboards: %w", err)
	}

	items := make([]*Dashboard, 0, len(rows))
	for i := range rows {
		items = append(items, modelDashboardToGQL(&rows[i]))
	}
	return &DashboardsResult{
		Items:    items,
		PageInfo: buildPageInfo(total, p, l),
	}, nil
}

// Dataset is the resolver for the dataset field.
func (r *queryResolver) Dataset(ctx context.Context, id string) (*Dataset, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	row, err := r.DatasetRepo.GetByID(ctx, id, userID)
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, nil
		}
		return nil, fmt.Errorf("get dataset: %w", err)
	}
	return modelDatasetToGQL(row), nil
}

// Datasets is the resolver for the datasets field.
func (r *queryResolver) Datasets(ctx context.Context, page *int, limit *int) (*DatasetsResult, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	p, l := pageDefaults(page, limit)

	rows, total, err := r.DatasetRepo.List(ctx, userID, p, l)
	if err != nil {
		return nil, fmt.Errorf("list datasets: %w", err)
	}

	items := make([]*Dataset, 0, len(rows))
	for i := range rows {
		items = append(items, modelDatasetToGQL(&rows[i]))
	}
	return &DatasetsResult{
		Items:    items,
		PageInfo: buildPageInfo(total, p, l),
	}, nil
}

// Charts is the resolver for the charts field — charts for a specific dataset.
func (r *queryResolver) Charts(ctx context.Context, datasetID string) ([]*SavedChart, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}

	var rows []models.SavedChart
	if err := r.DB.WithContext(ctx).
		Where("user_id = ? AND dataset_id = ?", userID, datasetID).
		Order("created_at desc").
		Find(&rows).Error; err != nil {
		return nil, fmt.Errorf("charts by dataset: %w", err)
	}

	// Batch-load dataset to attach on each chart.
	loader := loaderFromCtx(ctx)
	if loader != nil {
		loader.Schedule(datasetID)
		if ferr := loader.Flush(ctx); ferr != nil {
			return nil, ferr
		}
	}

	out := make([]*SavedChart, 0, len(rows))
	for i := range rows {
		ch := modelChartToGQL(&rows[i])
		if loader != nil {
			ch.Dataset = loader.Get(rows[i].DatasetID)
		}
		out = append(out, ch)
	}
	return out, nil
}

// MyCharts is the resolver for the myCharts field — all charts for the user.
func (r *queryResolver) MyCharts(ctx context.Context, page *int, limit *int) (*ChartsResult, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	p, l := pageDefaults(page, limit)

	rows, total, err := r.ChartRepo.List(ctx, userID, p, l)
	if err != nil {
		return nil, fmt.Errorf("list charts: %w", err)
	}

	// Batch-load all datasets for charts in this page.
	loader := loaderFromCtx(ctx)
	if loader != nil {
		for i := range rows {
			loader.Schedule(rows[i].DatasetID)
		}
		if ferr := loader.Flush(ctx); ferr != nil {
			return nil, ferr
		}
	}

	items := make([]*SavedChart, 0, len(rows))
	for i := range rows {
		ch := modelChartToGQL(&rows[i])
		if loader != nil {
			ch.Dataset = loader.Get(rows[i].DatasetID)
		}
		items = append(items, ch)
	}
	return &ChartsResult{
		Items:    items,
		PageInfo: buildPageInfo(total, p, l),
	}, nil
}

// Kpis is the resolver for the kpis field.
func (r *queryResolver) Kpis(ctx context.Context, page *int, limit *int) (*KpisResult, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	p, l := pageDefaults(page, limit)
	offset := (p - 1) * l

	var rows []models.KPI
	var total int64
	q := r.DB.WithContext(ctx).Where("user_id = ? AND deleted_at IS NULL", userID)
	if err := q.Model(&models.KPI{}).Count(&total).Error; err != nil {
		return nil, fmt.Errorf("count kpis: %w", err)
	}
	if err := q.Offset(offset).Limit(l).Order("created_at desc").Find(&rows).Error; err != nil {
		return nil, fmt.Errorf("list kpis: %w", err)
	}

	items := make([]*Kpi, 0, len(rows))
	for i := range rows {
		items = append(items, modelKPIToGQL(&rows[i]))
	}
	return &KpisResult{
		Items:    items,
		PageInfo: buildPageInfo(total, p, l),
	}, nil
}

// Alerts is the resolver for the alerts field.
func (r *queryResolver) Alerts(ctx context.Context, page *int, limit *int) (*AlertsResult, error) {
	userID, err := userIDFromCtx(ctx)
	if err != nil {
		return nil, err
	}
	p, l := pageDefaults(page, limit)

	// DataAlertRepository.List returns all (no pagination in the interface).
	// We apply manual pagination here to stay consistent with the GraphQL spec.
	rows, err := r.AlertRepo.List(ctx, userID)
	if err != nil {
		return nil, fmt.Errorf("list alerts: %w", err)
	}

	total := int64(len(rows))
	offset := (p - 1) * l
	end := offset + l
	if offset > len(rows) {
		offset = len(rows)
	}
	if end > len(rows) {
		end = len(rows)
	}
	page_rows := rows[offset:end]

	items := make([]*DataAlert, 0, len(page_rows))
	for i := range page_rows {
		items = append(items, modelAlertToGQL(&page_rows[i]))
	}
	return &AlertsResult{
		Items:    items,
		PageInfo: buildPageInfo(total, p, l),
	}, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
